### ISSUE TITLE
The Chinese translation encoding (Big5)

### ISSUE THREAD

**Issue by GitXarmoron** [PaweX/Settlers_IV_Language_Translations#4]
Using the tool, the new project build a file: s4_texts.dat7, but the game font display is abnormal, the new translation is not displayed, and it is still displayed in English, can you give me specific guidance, or help me generate a s4_texts.dat7 initial file or project, I will continue to modify.

Here are a few translations to give you:

gold - 黄金
wood - 木材
Tutorial - 教学关卡
Add on - 添加
Mission CD - 任务光盘
Single Player - 单人游戏
Multiplayer - 多人游戏
Load Game - 加载游戏
Exit - 退出游戏

Thank you so much for all you do

**Comment by GitXarmoron** [comment]
change MISCDATA1->Language = 7,the game font display is abnormal, the new translation is not displayed, and it is still displayed in English

![02](https://github.com/PaweX/Settlers_IV_Language_Translations/assets/149239945/a951c581-2b28-4471-96bf-80e245fcdadc)

**Comment by PaweX** [comment]
@GitXarmoron I will try to investigate it

> wood - 木材

Settlers uses 'planks' word instead, the word 'wood' is not used.


> change MISCDATA1->Language = 7,the game font display is abnormal, the new translation is not displayed, and it is still displayed in English

Not MISCDATA1.
Go to _Documents_/_TheSettlers4_/_Config_ -> edit **GameSettings.cfg** -> find **Language =** -> change to **7**.
Take the file "**s4_texts.dat7**" from this GitHub project, I've just added it.

**Comment by PaweX** [comment]
Some of the characters you used are not working in Settlers 4. The game doesn't use unicode because it's too old, it uses single byte characters instead. It seems it uses **Big5 encoding** but I am not 100% sure. But in Big5 encoding, the phrase “退出游戏” is converted to “退出遊戲” - and it works in S4 as you can see below:

![obraz](https://github.com/PaweX/Settlers_IV_Language_Translations/assets/3579486/77f3c21e-eb46-4fbc-9394-7afac91572ea)


P.S. I had some issues with the translating program, it doesn't seem to be very stable on non-lating alphabets or maybe it's also Win10 (I created it on Win7). Just make backups, you can also edit the **CHINESE.s4_translation_project** by a different text editor e.g. Notepad++. But be careful to not remove any lines that start wih '*' or '#'. I can help you in the future.

Also: don't use **(EXPERT) ICONV** options. If the program complains about converting characters, they most likely won't work in the game. If you use **(EXPERT) ICONV Ignore** flag, the program won't save the problematic characters and they will disappear.

**Comment by PaweX** [comment]
I asked ChatGPT to convert those words to **Big5** encoding:

**gold** (_黄金_) - 黃金
**planks**
**Tutorial** (_教学关卡_) - 教學關卡
**Add on** (_添加_) - 添加
**Mission CD** (_任务光盘_) - 任務光盤
**Single Player** (_单人游戏_) - 單人遊戲
**Multiplayer** (_多人游戏_) - 多人遊戲
**Load Game** (_加载游戏_) - 加載遊戲
**Exit** (_退出游戏_) - 退出遊戲

**Comment by GitXarmoron** [comment]
Thank you for your patient reply, great, it can be displayed now.
But the font is still abnormal, I'll look into it again:

![image](https://github.com/PaweX/Settlers_IV_Language_Translations/assets/149239945/4505ba5a-9778-4a3d-8780-f831bb3cfbd4)

**Comment by PaweX** [comment]
If you think you can do something about it, try. But why I have different font than you? Maybe you set smaller screen resolution?

P.S. Do you work on History Edition?
